// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _33_EF_LifeCycleTrackingSeedData.Contexts;

#nullable disable

namespace _33_EF_LifeCycleTrackingSeedData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_33_EF_LifeCycleTrackingSeedData.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"), 1L, 1);

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            FirstName = "Furkan",
                            LastName = "ERGÜL"
                        },
                        new
                        {
                            AuthorId = 2,
                            FirstName = "FF",
                            LastName = "loser"
                        });
                });

            modelBuilder.Entity("_33_EF_LifeCycleTrackingSeedData.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 1L, 1);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            Title = "İntihar Mektuplarım"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2,
                            Title = "Kaybolmuş Anahtarlar"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 2,
                            Title = "Şehrin En Güzel Manzarası"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 1,
                            Title = "Delinin Gözyaşları"
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 1,
                            Title = "Kargalar"
                        });
                });

            modelBuilder.Entity("_33_EF_LifeCycleTrackingSeedData.Models.Book", b =>
                {
                    b.HasOne("_33_EF_LifeCycleTrackingSeedData.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("_33_EF_LifeCycleTrackingSeedData.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
